#!/bin/bash

# Update package lists
apt-get update
apt-get upgrade -y

# Install required packages
apt-get install -y apache2 \
                    ghostscript \
                    libapache2-mod-php \
                    php \
                    php-bcmath \
                    php-curl \
                    php-imagick \
                    php-intl \
                    php-json \
                    php-mbstring \
                    php-mysql \
                    php-xml \
                    php-zip \
                    unzip \
                    curl \
                    mysql-client

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

unzip awscliv2.zip

sudo ./aws/install

# Optionally, start Apache service
systemctl start apache2
systemctl enable apache2

# Set proper permissions
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html

# Remove the default Apache index.html file
rm -rf cd/var/wwww/html

aws s3 sync s3://armirbucket/my_arch.zip /var/www/wordpress.zip   
unzip /var/www/wordpress.zip  

# Update DB_CHARSET in wp-config.php
sed -i "s/define('DB_CHARSET', 'utf8mb4');/define('DB_CHARSET', 'utf8');/" /var/www/html/wp-config.php

# Add WP_HOME and WP_SITEURL to wp-config.php
echo "define('WP_HOME', '$SITE_URL');" >> /var/www/html/wp-config.php
echo "define('WP_SITEURL', '$SITE_URL');" >> /var/www/html/wp-config.php

# Set the proper permissions for wp-config.php
chown www-data:www-data /var/www/html/wp-config.php
chmod 640 /var/www/html/wp-config.php
