#!/bin/bash

# Update package lists
apt-get update
apt-get upgrade -y

# Install required packages
apt-get install -y apache2 \
                    ghostscript \
                    libapache2-mod-php \
                    php \
                    php-bcmath \
                    php-curl \
                    php-imagick \
                    php-intl \
                    php-json \
                    php-mbstring \
                    php-mysql \
                    php-xml \
                    php-zip \
                    unzip \
                    curl \
                    mysql-client

# Install AWS CLI
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "./awscliv2.zip"
unzip ./awscliv2.zip
sudo ./aws/install

# Ensure /var/www/html exists and remove default index.html
rm -rf /var/www/html


# Fetch and unzip the file from S3 into /var/www/
aws s3 cp s3://armirbucket/my_arch.zip /var/www/
unzip /var/www/my_arch.zip -d /var/www/


# Update DB_CHARSET in wp-config.php
sed -i "s/define('DB_CHARSET', 'utf8mb4');/define('DB_CHARSET', 'utf8');/" /var/www/html/wp-config.php


# Set proper permissions
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html

# Set permissions for wp-config.php
chown www-data:www-data /var/www/html/wp-config.php
chmod 640 /var/www/html/wp-config.php

# Start and restart Apache to serve the content
systemctl start apache2
systemctl enable apache2
systemctl restart apache2
